CREATE TABLE NODE_SUBSCRIPTIONS ( 
ID VARCHAR(256) PRIMARY KEY NOT NULL,
SUBSCRIPTION_ID VARCHAR(256), 
NODE_ID VARCHAR(50) NOT NULL,
CREATED TIMESTAMP,
FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES EVENTS(ID),
FOREIGN KEY (NODE_ID) REFERENCES NODES(ID)
);